[package]
name = "botnet-macros"
description = "Botnet code generation."
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lib]
proc-macro = true

[dependencies]
botnet-utils = { path = "./../botnet-utils", version = "0.2" }
proc-macro-error = "1.0"
proc-macro2 = "1.0"
quote = "1"
syn = { version = "1.0", features = ["full"] }
