[package]
name = "botnet-macros"
version = "0.2.0"
edition = "2021"
license = "BUSL-1.1"
repository = "https://github.com/ra0x3/botnet"
description = "botnet"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
botnet-utils = { path = "./../botnet-utils", version = "0.1" }
proc-macro-error = "1.0"
proc-macro2 = "1.0"
quote = "1"
syn = { version = "1.0", features = ["full"] }
