FROM ubuntu:22.04

WORKDIR /app

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt-get upgrade -y
RUN apt install software-properties-common -y
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt install -y \
    libpq-dev \
    build-essential \
    python3.9 \
    python3.9-dev \
    python3.9-venv \
    python3.9-distutils \
    python3.9-lib2to3 \
    python3.9-gdbm

COPY . .

RUN python3.9 -m venv venv
RUN ./venv/bin/pip install -r requirements/requirements.txt

EXPOSE 8000

CMD exec ./venv/bin/python3.9 main.py --pg_host "${pg_host}" --pg_port "${pg_port}" --pg_user "${pg_user}" --pg_password "${pg_password}" --pg_database "${pg_database}"

# docker run -it -p 8000:8000 -e "pg_host=6.tcp.ngrok.io" -e "pg_port=19705" -e "pg_user=postgres" -e "pg_database=bitsy" bitsy/py:latest
