FROM ubuntu:22.04

RUN apt update && apt install -y build-essential \
    libcurl4-gnutls-dev \
    libxml2-dev \
    libssl-dev \
    software-properties-common \
    curl

RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
RUN apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
RUN apt update && apt install vault -y

EXPOSE 8200

RUN apt-get install --reinstall -y vault

CMD vault server -config /etc/vault.d/vault.hcl

# docker run -it -p 8200:8200 --cap-add=IPC_LOCK ralston3/bitsy-vault:latest
