version: "3.9"  # optional since v1.27.0
services:
  bitsy-vault:
    build:
      dockerfile: ./Dockerfile.bitsy.vault
    cap_add:
      - IPC_LOCK
    environment:
      - ENV=prod
    env_file: ./../../env/.env.prod
    ports:
      - "8002:8002"
    volumes:
      - .:/usr/local/bitsy-vault
      - logvolume01:/var/log
  bitsy-py:
    image: ralston3/bitsy:py-latest
    env_file: ./../../env/.env.prod
    environment:
      - ENV=prod
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_PASSWORD=${PG_PASSWORD}
      - API_HOST=0.0.0.0
      - API_PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/local/bitsy-py
      - logvolume01:/var/log
    depends_on:
      - bitsy-vault
    links:
      - "bitsy-vault"
  bitsy-rs:
    image: ralston3/bitsy:rs-latest
    environment:
      - ENV=prod
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_PASSWORD=${PG_PASSWORD}
      - HOST=0.0.0.0
      - PORT=8080
    env_file: ./../../env/.env.prod
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/local/bitsy-rs
      - logvolume01:/var/log
    depends_on:
      - bitsy-py
  bitsy-www:
    image: ralston3/bitsy:www-latest
    environment:
      - ENV=prod
      - REACT_APP_PROTOCOL=http
      - REACT_APP_BITSY_API_HOST=bitsy-rs
      - REACT_APP_BITSY_API_PORT=8000
    env_file: ./../../env/.env.prod
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/local/bitsy-www
      - logvolume01:/var/log
    depends_on:
      - bitsy-py
    links:
      - "bitsy-vault"
volumes:
  logvolume01: {}
