version: v1
plan:
  entity:
    enabled: true
    class: IPUAEntityCounter
  anonimity:
    kanonimity:
      enabled: true
      k: 100
      class: KAnonimity
  limiter:
    enabled: true
    version: 100
    class: CliffDetector
keys:
  - name: http
    fields:
      - name: ssl
        key: ssl
        description: SSL parameter.
        extractor: UrlExtractor
      - name: region
        key: region
        description: Region parameter.
        extractor: UrlExtractor
  - name: ip
    fields:
      - name: ip
        key: ip
        description: IP address.
        extractor: IPExtractor
database:
  db_type: in_memory
  uri: ~

