[package]
name = "botnet"
version = "0.2.0"
edition = "2021"
license = "BUSL-1.1"
repository = "https://github.com/ra0x3/botnet"
description = "botnet"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "botnet"
path = "src/bin/main.rs"

[lib]
name = "botnet"
path = "src/lib.rs"

[dependencies]
async-std = { version = "1.0", optional = true }
async-trait = { version = "0.1", optional = true }
axum = { version = "0.6", optional = true }
bincode = { version = "1.3", optional = true }
botnet-core = { path = "./../botnet-core", version = "0.2" }
botnet-macros = { path = "./../botnet-macros", version = "0.2" }
botnet-utils = { path = "./../botnet-utils", version = "0.2" }
bytes = { version = "1.3", features = ["serde"], optional = true }
clap = { version = "4.2", features = ["derive"], optional = true }
nom = { version = "5.1", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
thiserror = { version = "1.0", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.3", features = ["fs", "trace", "cors", "limit"], optional = true }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
url = { version = "2.3", optional = true }

[features]
default = ["binutils"]
binutils = [
    "async-std",
    "async-trait",
    "axum",
    "bincode",
    "bytes",
    "clap",
    "nom",
    "serde",
    "serde_json",
    "thiserror",
    "tokio",
    "tower",
    "tower-http",
    "url"
]