[package]
name = "botnet"
version = "0.2.0"
edition = "2021"
license = "BUSL-1.1"
repository = "https://github.com/ra0x3/botnet"
description = "botnet"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "botnet"
path = "src/bin/main.rs"

[dependencies]
async-std = "1.0"
async-trait = "0.1"
axum = "0.6"
bincode = "1.3"
botnet-core = { path = "./../botnet-core", version = "0.2" }
botnet-macros = { path = "./../botnet-macros", version = "0.2" }
botnet-utils = { path = "./../botnet-utils", version = "0.2" }
bytes = { version = "1.3", features = ["serde"] }
nom = "5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4" }
tower-http = { version = "0.3", features = ["fs", "trace", "cors", "limit"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3" }
url = "2.3"
