[package]
name = "botnet"
description = "Botnet middleware."
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lib]
name = "botnet"
path = "src/lib.rs"

[dependencies]
async-std = { version = "1.0" }
axum = { version = "0.6" }
botnet-core = { path = "./../botnet-core", version = "0.2" }
botnet-macros = { path = "./../botnet-macros", version = "0.2" }
botnet-utils = { path = "./../botnet-utils", version = "0.2" }
futures-util = "0.3"
tower = { version = "0.4" }
tower-http = { version = "0.3", features = ["fs", "trace", "cors", "limit"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["ansi", "json", "env-filter"] }
