[package]
name = "botnet"
description = "Botnet middleware."
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[[bin]]
name = "botnet"
path = "src/bin/main.rs"

[lib]
name = "botnet"
path = "src/lib.rs"

[dependencies]
async-std = { version = "1.0", optional = true }
async-trait = { version = "0.1", optional = true }
axum = { version = "0.6", optional = true }
bincode = { version = "1.3", optional = true }
botnet-core = { path = "./../botnet-core", version = "0.2" }
botnet-macros = { path = "./../botnet-macros", version = "0.2" }
botnet-utils = { path = "./../botnet-utils", version = "0.2" }
bytes = { version = "1.3", features = ["serde"], optional = true }
clap = { version = "4.2", features = ["derive"], optional = true }
futures-util = "0.3"
lazy_static = "1.4"
nom = { workspace = true, optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
thiserror = { version = "1.0", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
tower = { version = "0.4", optional = true }
tower-http = { version = "0.3", features = ["fs", "trace", "cors", "limit"], optional = true }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["ansi", "json", "env-filter"] }
url = { version = "2.3", optional = true }

[features]
default = ["binutils"]
binutils = [
    "async-std",
    "async-trait",
    "axum",
    "bincode",
    "bytes",
    "clap",
    "nom",
    "serde",
    "serde_json",
    "thiserror",
    "tokio",
    "tower",
    "tower-http",
    "url"
]