[package]
name = "botnet-core"
description = "Botnet core middleware."
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
async-trait = "0.1"
bincode = "1.3"
botnet-utils = { path = "./../botnet-utils", version = "0.2" }
bytes = { version = "1.3", features = ["serde"] }
http = { version = "0.2" }
nom = { workspace = true }
redis = { version = "0.22", default-features = false, optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
url = "2.3"

[features]
default = []
redisdb = ["redis"]
