keystore_provider: vault
vault_address: http://host.docker.internal:8200
log_level: DEBUG
log_file: bitsy.log
workers: 3
api_host: "0.0.0.0"
api_port: "8000"
pg_database: "bitsy"
pg_user: "postgres"
pg_password: ""
pg_host: "127.0.0.1"
pg_port: "5432"
env: prod
